config/routes.rb
Rails.application.routes.draw do
  
  get 'petsearch/index'

  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'pets/search' => 'pets#search'
  get 'demo/sample' => 'demo#sample'

  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :photos
  resources :pets
  resources :profiles
  resources :users

  root 'home#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  # Makes a profile rateable
  ratyrate_rateable 'trust'
  
  # Makes it possible to apply permissions
  resourcify

  # Fill geolocation data
  acts_as_mappable :lat_column_name => :lat,
                   :lng_column_name => :long
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    if current_user.profile.present?
      respond_to do |format|
       format.html { redirect_to @profile, notice: 'Can\'t create more than one profile!' }
       format.json { render :show, status: :created, location: @profile }
      end
    else
      @profile = Profile.new
      location = session[:geo_location]
      @profile.lat = location["lat"]
      @profile.long = location["lng"]
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:avatar, :first_name, :last_name, :email, :lat, :long, :user_id)
    end
  end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for @profile do |f| %>
  <%= f.input :avatar %>
  <%= f.input :first_name %>
  <%= f.input :last_name%>
  <%= f.input :email%>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  <%= f.button :submit%>
<% end %>

app/views/profiles/edit.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/index.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="son">
      <%= image_tag "young_man.jpg", :alt => "profile", :title => "youngman"%>
    </div>
    <div>
      <table class="table">
        <tbody>
          <tr>
            <th>Name</th>
          </tr>
          <tr>
            <td>myname</td>
          </tr>
          <tr>
            <th>Last Name</th>
          </tr>
          <tr>
            <td>mylastname</td>
          </tr>
          <tr>
            <th>E-mail</th>
          </tr>
          <tr>
            <td>myemail</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-8">
    <div class="col-md-4">  
    <%= image_tag "perro_profile.png", :alt => "petprofile", :title => "petprofile"%>
    </div>  
    <div class="col-md-8">
      <table class="table table-striped">
        <tbody>
          <tr>
            <th>Breed:</th>
            <td>""</td>
          </tr>
          <tr>
            <th>Age:</th>
            <td>""</td>
          </tr>
          <tr>  
            <th>Pedigree:</th>
            <td>""</td>
          </tr>
          <tr>
            <th>Date of birth:</th>
            <td>""</td>
          </tr>
          <tr>
            <th>Details:</th>
            <td>""</td>
          </tr>
          
        </tbody>
      </table>
      <%= link_to t('.new', :default => t("helpers.links.new")),
            new_profile_path,
            :class => 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/profiles/show.html.erb
<%- model_class = Profile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="mycontainer">
  <div class="row">
    <div class="col-md-4">
      <div class="son">
        <%= image_tag @profile.avatar.url(:medium) %>
      </div>
      <%= label :first_name, model_class.human_attribute_name(:first_name) %>
      <%= text_field :first_name, :first_name, :class => "form-control", :value => @profile.first_name %>
      <%= label :last_name, model_class.human_attribute_name(:last_name) %>
      <%= text_field :last_name, :last_name, :class => "form-control", :value => @profile.last_name%>
      <%= label :email, model_class.human_attribute_name(:email) %>
      <%= text_field :email, :email, :class => "form-control", :value => @profile.email %>

      <%  if can? :edit, @profile %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_profile_path(@profile), :class => 'btn btn-default' %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="son2">
        <% if @profile.user.id == current_user.id%>
        <%= link_to t('.new', :default => t("helpers.links.new")),    new_pet_path, :class => 'btn btn-default' %>
        <% end %>
      </div>
      <% @profile.user.pets.each do |pet| %>
      <div class="row">
        <div class="col-md-4">
          <% if pet.photos.present? %>
            <%= image_tag pet.photos.first.picture.url(:thumb) %>
          <% else %>
            <strong> No picture! </strong>
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="text-right">
          <table class="table table-striped">
            <colgroup>
              <col class="col-md-3">
              <col class="col-md-9">
            </colgroup>
            <tbody>
              <tr>
                <th>Name:</th>
                <td><%= pet.name %></td>
              </tr>
              <tr>
                <th>Breed:</th>
                <td><%= pet.breed %></td>
              </tr>
              <tr>  
                <th>Pedigree:</th>
                <td><%= pet.pedigree_value %></td>
              </tr>
              <tr>
                <th>More info:</th>
                <td><%= link_to "Show info", pet_path(pet.id), :class => 'btn btn-default' %></td>
              </tr>
              
            </tbody>
          </table>
          </div>
        </div>
        
        </div>
      <% end %> 
      </div>
    </div>
  </div>
</div>