config/routes.rb
Rails.application.routes.draw do
  
  get 'petsearch/index'

  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'pets/search' => 'pets#search'
  get 'demo/sample' => 'demo#sample'

  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :photos
  resources :pets
  resources :profiles
  resources :users

  root 'home#index'

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
      @pets = Pet.search(params[:name],params[:breed],params[:pedigree],params[:gender]).order("created_at DESC")
  end
  
  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to profile_path(current_user.profile.id), notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to profile_path(current_user.profile.id), notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :pedigree, :born_at, :about, :gender, :user_id)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :breed, :as => :select, :collection => Pet.breeds%>
  <%= f.input :pedigree%>
  <%= f.input :born_at%>
  <%= f.input :about%>
  <%= f.input :gender, :as => :select, :collection => Pet.genders%>
  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
  <%= f.button :submit%>
<% end %>

app/views/pets/edit.html.erb
<%- model_class = Pet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pets/index.html.erb
<%- model_class = Pet -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<h2> Search </h2>

<%= form_tag pets_path, :method => 'get' do %>
<%= label :name, "Name" %>
<%= text_field_tag :name %>
<%= label :breed, "Breed" %>
<%= select_tag :breed, options_for_select(Pet.breeds), :include_blank => true %>
<%= label :pedigree, "Pedigree" %>
<%= check_box_tag :pedigree %>
<%= label :gender, "Gender" %>
<%= select_tag :gender, options_for_select(Pet.genders), :include_blank => true %>
<%= submit_tag "Search", :name => nil %>
<% end %>

<thead>
  <div class="parent">
    <div class="son2">
      <iframe width="640" height="360" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3901.1283486274506!2d-76.96472486492686!3d-12.10336482643578!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9105c70ab77498c1%3A0xcce9f50642e7c684!2sUniversidad+Peruana+de+Ciencias+Aplicadas!5e0!3m2!1ses-419!2spe!4v1446737353864" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
  </div>
</thead>
<table class="table">
  <tbody>
      <tr>
        <th>Near pets</th>
      </tr>
  </tbody>
</table>
<div class"centered">
  <% @pets.each do |pet| %>
  <div class="col-md-4">  
    <% if pet.photos.present? %>
      <%= image_tag pet.photos.first.picture.url(:thumb) %>
    <% else %>
      <strong> No picture! </strong>
    <% end %>
  </div>  
  <div class="col-md-8">
    <div class="text-right">
    <table class="table table-striped">
      <colgroup>
        <col class="col-md-3">
        <col class="col-md-9">
      </colgroup>
      <tbody>
        <tr>
          <th>Name:</th>
          <td><%= pet.name %></td>
        </tr>
        <tr>
          <th>Breed:</th>
          <td><%= pet.breed %></td>
        </tr>
        <tr>  
          <th>Pedigree:</th>
          <td><%= pet.pedigree_value %></td>
        </tr>
        <tr>
          <th>Gender:</th>
          <td><%= pet.gender %></td>
        </tr>
        <tr>
          <th>More details:</th>
          <td><%= link_to "Show info", pet_path(pet.id), :class => 'btn btn-default' %></td>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<%- model_class = Pet -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pets/show.html.erb
<%- model_class = Pet -%>
<div class="mycontainer">
  <div class="page-header">
    <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
  </div>
  
  <div class="row">
    <div class="col-md-6">
      <div class="son">
        <% if @pet.photos.present? %>
        <%= link_to image_tag(@pet.photos.first.picture.url(:medium)), (photos_url(pet_id: @pet.id)) %>
        <br>
        <% else %>
        <strong> No images yet! Would you like to add some? </strong>
        <br>
        <% end %>
      </div>
        <%= link_to "Add new picture!", new_photo_path(:pet_id => @pet.id)%>
      <table class="table table-striped">
        <tbody>
          <tr>
            <th><%= label :name, model_class.human_attribute_name(:name) %></th>
          </tr>
          <tr>
            <td>
              <%= @pet.name %>
            <td>
          </tr>
          <tr>
            <th><%= label :breed, model_class.human_attribute_name(:breed) %></th>
          </tr>
          <tr>
            <td>
              <%= @pet.breed %>
            <td>
          </tr>
          <tr>
            <th><%= label :born_at, "Date of Birth" %></th>
          </tr>
          <tr>
            <td>
              <%= @pet.born_at %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <table class="table table-striped">
        <tbody>
          <tr>
            <th><%= label :gender, model_class.human_attribute_name(:gender) %></th>
          </tr>
          <tr>
            <td>
              <%= @pet.gender %>
            </td>
          </tr>
          <tr>
            <th><%= label :pedigree, model_class.human_attribute_name(:pedigree) %></th>
          </tr>
          <tr>
            <td>
              <%=  @pet.pedigree_value %>
            </td>
          </tr>
        </tbody>
      </table>
  
      <%= label :about, "Details" %>
        <dd><%=  @pet.about %></dd>
      
      <% if can? :update, @pet %> 
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_pet_path(@pet), :class => 'btn btn-default' %>
      <% end %>

      <%= link_to "Contact owner", profile_path(@pet.user.profile.id), :class => 'btn btn-default' %>
    </div>
  </div>
</div>