config/routes.rb
Rails.application.routes.draw do
  
  get 'petsearch/index'

  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'pets/search' => 'pets#search'
  get 'demo/sample' => 'demo#sample'

  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :photos
  resources :pets
  resources :profiles
  resources :users

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<body class="aboutbackground">    
    <div class="container">
        <div class="header-section">
            <h2 class="section-heading ">About us</h2>
            <span class="section-sub-heading">Your pet also needs some fun</span>
        </div>
        <div class="about-text">
            <p id="aboutp">
                We are a group of people who know how important a pet can be to us.
                
                We think that pets are family, so that we need to find the best partner to our lovely friend.
    
                We want to promote the love for our pets and make PetApp community the first and best community where you can easily find the perfect partner for your little friend.

                <%= current_user.authentication_token %>
                <%= current_user.email %>
    
            </p>
        </div>
        <!--
        <div class="section-image  wow fadeInUp">
            <span class="img-mid"><img id="weblogo" src="mid-star.png" alt="about us"></span>
        </div>
        -->
    </div>
</body>

app/views/home/index.html.erb
<body class="petbackgroundtwo">
<div class="row">
    <div class="col-lg-9">
      <h1>Welcome to PetApp Community </h1>
        <div class="text-center">
        <h2>
            <span class="rotate">Join the largest Pet Network, nice people with nice pets, because your pet also has its needs, biggest pet community in Peru</span>
        </h2>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
          </ol>
        
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <div class="parent">
                  <%= image_tag "p1.jpg", :alt => "", :title => "perros1"%>
                  <div class="carousel-caption">
                    <h3>divinos</h3>
                    <p>Tex1.</p>
                  </div>
              </div>
            </div>
        
            <div class="item">
              <div class="parent">
                  <%= image_tag "p2.jpg", :alt => "", :title => "perros2"%>
                  <div class="carousel-caption">
                    <h3>bonitos</h3>
                    <p>Tex2.</p>
                  </div>
              </div>
            </div>
        
            <div class="item">
              <div class="parent">
                  <%= image_tag "p3.jpg", :alt => "", :title => "perros3"%>
                  <div class="carousel-caption">
                    <h3>feos</h3>
                    <p>Text3.</p>
                  </div>
              </div>  
            </div>
        
            <div class="item">
              <div class="parent">
                  <%= image_tag "p4.jpg", :alt => "", :title => "perros4"%>
                  <div class="carousel-caption">
                    <h3>raros</h3>
                    <p>Text4.</p>
                  </div>
              </div>
            </div>
          </div>
        
          <!-- Left and right controls 
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>-->
          <a class="carousel-control left" data-slide="prev" href="#myCarousel"></a>
          <a class="carousel-control right" data-slide="next" href="#myCarousel"></a>
        </div>
        </div>
    </div>
    
    <% if !user_signed_in? %>
    <div class="col-lg-3">
        <div class="well sidebar-nav">
            <h3 class="text-center">Log in</h3>
            <ul class="nav nav-list">
                <li class="nav-header"></li>
                <%= form_for(:user, :url => session_path(:user)) do |f| %>
                
                <table>
                    <tr>
                        <td><%= f.label :email %></td>
                    </tr>
                    <tr>
                        <td><%= f.text_field :email %></td>
                    </tr>
                    <tr>
                        <td><%= f.label :password %></td>
                    </tr>
                    <tr>
                        <td><%= f.password_field :password %></td>
                    </tr>
                    <tr>
                        <td><%= f.check_box :remember_me %>
                        <%= f.label :remember_me %></td>
                    </tr>
                    <tr>
                        <td><%= f.submit 'Sign in' %></td>
                    </tr>
                    <tr>
                        <td><%= link_to "Forgot your password?", new_password_path(:user) %></td>
                    </tr>
                    <td><%= link_to('Join us!', new_user_registration_path)  %>  
                    <tr class="text-center">
                        <td><%= f.label :Log_in_with %></td>
                    </tr>
                    <tr class="footer-social-icon text-center">
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </td>
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </td>
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </td>
                    </tr>
                </table>
                <% end %>
            </ul>
        </div><!--/.well -->
    </div><!--/span-->
    <% end %>
    
</div>
<!--preloader-init,royal_preloader-->
<script>
        $(document).ready(function () {
            // banner text rotator
            $(".rotate").textrotator({
                animation: "dissolve", //opciones de cambio entre mensajes: (default), fade, flip, flipUp, flipCube, flipCubeUp and spin.
                separator: ",", // separador
                speed: 3000 // tiempo
            });

            //  full transparent and half transparent menu apper bg color

            $(window).on("scroll", function () {
                if ($(".full-transparent, .semi-transparent").length > 0) {
                    var wh = $(window).height();
                    if ($(window).scrollTop() > wh) {
                        if (!$(".full-transparent, .semi-transparent").hasClass("navbg"))
                            $(".full-transparent, .semi-transparent").addClass("navbg");
                    } else {
                        if ($(".full-transparent, .semi-transparent").hasClass("navbg"))
                            $(".full-transparent, .semi-transparent").removeClass("navbg");
                    }
                }
            });
        });
</script>
</body>