config/routes.rb
Rails.application.routes.draw do
  
  get 'petsearch/index'

  get 'index' => 'home#index'
  get 'about' => 'home#about'
  get 'pets/search' => 'pets#search'
  get 'demo/sample' => 'demo#sample'

  post '/rate' => 'rater#create', :as => 'rate'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions"}
  resources :photos
  resources :pets
  resources :profiles
  resources :users

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new 
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :person
      can :read, :all
      can [:update,:destroy], Profile, :user_id => user.id  
      can :create, Profile, :user_id => user.id
      can [:update,:destroy], Pet, :user_id => user.id  
      can :create, Pet, :user_id => user.id
      can [:update,:destroy], Photo, :pet_id => user.pets.ids
      can :create, Photo
    else
      can :read, :all
    end
  end
end
    

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :pet
  validates :pet, presence: true
  has_attached_file :picture, styles: { medium: "300x300>", thumb: "125x125>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/


  resourcify

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  # Makes a profile rateable
  ratyrate_rateable 'trust'
  
  # Makes it possible to apply permissions
  resourcify

  # Fill geolocation data
  acts_as_mappable :lat_column_name => :lat,
                   :lng_column_name => :long
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_token_authenticatable
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  has_one :profile
  has_many :pets

  after_create :assign_default_role

  
  def assign_default_role
    add_role(:person)
  end  
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def sample
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
      @pets = Pet.search(params[:name],params[:breed],params[:pedigree],params[:gender]).order("created_at DESC")
  end
  
  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to profile_path(current_user.profile.id), notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to profile_path(current_user.profile.id), notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :breed, :pedigree, :born_at, :about, :gender, :user_id)
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Petapp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <link href="assets/stylesheets/themecolor.css" type="text/css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- Como se llaman a las hojas de estilos creadas??? -->

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" > <%= image_tag "logo_footer.png", :alt => "pet_app", :title => "petapp"%></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", index_path  %></li>

            <% if user_signed_in? %>
              <% if current_user.profile.present? %>
              <li><%= link_to "My Profile", profile_path(current_user.profile.id)  %></li>
              
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path  %></li>
              <% end %>
            <% end %>
            <li><%= link_to "Find Pet", pets_path  %></li>
            <li><%= link_to "About", about_path  %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="nav navbar-text">Logged in as <%= current_user.email %></li>
              <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="nav navbar-text"> Log in to get started</li>
              <li> <%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <div class="container">
    <%= yield %>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
        </div>
      </div>
      
      <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <tr class="footer-social-icon">
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </td>
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </td>
                        <td>
                            <a href="" target="_blank">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </td>
                    </tr>
                    <div class="footer-logo wow fadeInUp">

                        <a href="#"> <%= image_tag "logo_footer.png", :alt => "logo_footer", :title => "footer"%></a>

                    </div>
                    <div>
                        <p>&copy; 2015 All rights reserved. <a>Privacy Policy</a></p>
                    </div>
                </div>
            </div>
        </div>
      </footer>
    
    </div> <!-- /container -->

  </body>
</html>